name: Nest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare Env
        run: npm -g install @nest/cli

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run-script lint

      - name: Build
        run: npm run-script build

      - name: Run test suit
        run: npm run-script test
